# -*- coding: utf-8 -*-
"""Shared prompt text for harm-boundary reasoning."""


HARM_BOUNDARY_RULES = """Harm-boundary guidance for reasoning:
- Do not over-correct toward Claim_Harmless. These rules are meant to distinguish topic mention from harmful stance, not to excuse explicit harmful implications.
- Claim_Harmful requires an identifiable target plus a harmful stance or implication: endorsement, ridicule, dehumanization, objectification, stereotyping, threat, sexual entitlement, consent trivialization, or normalization of harm.
- Strong Claim_Harmful signals remain harmful even if the meme is humorous or ironic: rape/consent jokes, women-as-objects framing, protected-group inferiority claims, slurs, human-to-animal comparisons aimed at a group/person, celebration of violence, praise of hate groups, or victim-directed mockery.
- Sensitive-topic mention, depiction, OCR, or retrieval similarity alone is not enough for Claim_Harmful. Ask whether the meme endorses, mocks victims, or attacks a target, rather than merely mentioning the topic.
- Historical, educational, documentary, news-like, memorial, technical, or descriptive framing should not be treated as harmful by itself; it becomes harmful only when the meme celebrates perpetrators, mocks victims, or uses the topic to attack a target.
- Condemning, denouncing, exposing, or criticizing hate/violence usually weakens Claim_Harmful unless the image-text combination reverses that stance or makes the harmful ideology the joke to endorse.
- Political/public-figure/policy criticism is not automatically harmful, but it becomes harmful when it contains protected-group attack, dehumanization, explicit violence, or dangerous misinformation.
- Animals, weapons, disasters, illness, or violence-related words are not Claim_Harmful by themselves; identify a human/protected target and harmful stance first.
- If evidence only shows topic sensitivity or ambiguous association, support Claim_Harmless or weaken Claim_Harmful and record the ambiguity. If explicit harmful stance is present, support Claim_Harmful and explain why the boundary exception does not apply."""


FHM_BOUNDARY_ADDENDUM = """FHM-specific calibration:
- FHM is not only explicit hate speech. Claim_Harmful includes offensive meme implications that attack or degrade a person/group through protected identity, gender/sexual framing, disability, religion, race/ethnicity/nationality, animalization, objectification, violence, consent trivialization, victim mockery, terrorism/atrocity humor, or serious suffering used as the punchline.
- Many FHM positives are implicit image-text jokes. Do not require an explicit slur or threat when the combined image and caption create a clear offensive proposition: human-to-animal comparison, women-as-domestic-appliance/object/sex-role framing, trans or disability mockery, racialized color/food/animal wording, religious stereotype, child/victim humiliation, or tragedy/violence made funny.
- Treat coded or euphemistic captions as evidence when the image grounds the target. Examples of risky mechanisms include dishwasher/kitchen/sandwich jokes aimed at women, tampon/body jokes aimed at women, "vegetable" aimed at disabled/injured people, animal/ape/goat/pig comparisons aimed at people, Holocaust/colonialism/slavery/terrorism/9-11/war references used as punchlines, and "stop resisting"/police-violence jokes that mock the injured victim rather than critique the violence.
- But FHM is narrower than general offensiveness. A protected identity word, religion name, nationality, Hitler/Nazi/KKK/terrorism reference, sexual word, or coded object word is not enough by itself. Generic puns, historical descriptions, documentary captions, anti-hate commentary, jokes aimed at perpetrators/hate groups/terrorists rather than protected victims, and meta jokes about racism/hate are Claim_Harmless unless the image-text pair clearly assigns inferiority, criminality, sexual degradation, animalization, threat, or victim mockery to a protected target.
- Religious and nationality wordplay needs extra grounding. "Jew jitsu", "Nazi" puns, "Mohammed" wordplay, generic Muslim/Islam captions, German/Asian/white/black wordplay, or race/color puns should not become Claim_Harmful unless they are tied to a degrading stereotype, violence, terrorism generalized to the group, animal/object comparison, or explicit contempt for the group.
- Coded gender terms need target anchoring. Dishwasher/kitchen/sandwich/tampon/body/sex jokes support Claim_Harmful when they degrade women or people with periods through domestic-role, sexual, coercive, or body-shaming framing. The same words can be Claim_Harmless when they are only object puns, generic appliance/food jokes, or non-targeted crude humor.
- For borderline coded cases, compare the mechanism rather than the keyword: pun vs contempt, object/food wordplay vs human dehumanization, historical reference vs victim mockery, generic sex joke vs gendered sexual degradation, and standalone animal/pet joke vs human-animal comparison. Do not demand a perfect explicit target when the meme's implication is clear, but do not let a keyword alone decide the label.
- FHM false positives still matter: ordinary insult, slapstick, embarrassment, absurdity, arrest jokes, family/ex-partner jokes, pets/standalone animals, gross food jokes, sports/work jokes, and generic dark humor are Claim_Harmless when no protected/group-directed, gendered, sexual, violent, dehumanizing, consent-related, or victim-mocking mechanism is grounded by the image-text pair.
- Trivialization is harmful only when you can name the victim, group, or serious harm being mocked or normalized. If the meme merely mentions a sensitive topic in a historical, documentary, descriptive, anti-hate, or counter-speech way, prefer Claim_Harmless.
- The words stereotype, objectification, dehumanization, ridicule, and harmful implication must be grounded in concrete image-text evidence. Do not infer them from weak similarity to retrieved cases or from generic audience sensitivity.
- Human-animal comparisons are strong harmful evidence when the comparison is aimed at a person, protected group, or vulnerable victim. A standalone animal, zoo, pet, wildlife, or absurd animal juxtaposition is not enough.
- Keep strong harmful signals harmful: misogynistic sexual entitlement, rape/consent jokes, women-as-objects, explicit protected-group attack, slurs, identity inferiority, celebration of violence, and victim-directed mockery should support Claim_Harmful even if the meme is ironic, terse, or visually implicit."""


HARM_BOUNDARY_ADDENDUM = """HarM-specific calibration:
- HarM is broader and softer than FHM: Claim_Harmful includes "somewhat harmful" harms aimed at an individual, organization, community, or society. Do not require protected-group hate, explicit endorsement, or a direct instruction to cause harm.
- HarM often marks weak individual/political harm as positive. A named person or public figure can be the harmed target when the meme directly frames them as stupid, reckless, incompetent, corrupt, diseased, physically grotesque, morally deserving illness/death, or personally ridiculous. Ordinary policy criticism is different: criticizing an administration, delay, public funding, preparedness, or public conduct without personal degradation can remain Claim_Harmless.
- Use this HarM decision order: (1) identify who or what the joke is on; (2) decide whether the main punchline degrades a person/organization/community, mocks illness/death/vulnerability, or normalizes a risky public-health belief; (3) only then apply satire, public-figure, or counter-speech exceptions.
- COVID/political somewhat-harmful signals include: illness or diagnosis as deserved comeuppance; COVID personified as punishing someone; mask-wearing or testing used to ridicule a person; a public figure portrayed as medically dangerous, foolish, or unfit; pandemic response failure turned into personal humiliation; hoax/fake-news/deep-state/QAnon language made memorable; vaccine, mask, test, disinfectant, bleach, or cure misinformation presented as plausible or socially persuasive; and disease-origin stigma toward China/Chinese people or another community.
- Counter-speech, fact-checking, and expert condemnation are not automatically harmless in HarM. If the meme's dominant effect is to ridicule a named person as an idiot, dangerous fool, failed leader, sick victim, or deserved target, it can still be Claim_Harmful toward the individual. If the dominant effect clearly debunks or warns without personal degradation, victim mockery, or memorable amplification of the dangerous claim, support Claim_Harmless.
- Public-figure satire is harmless when the joke targets policy, abstract events, the virus itself, generic pandemic inconvenience, or political wordplay without degrading an individual and without normalizing public-health risk. "It is satire" or "the target is a public figure" is not enough by itself, but neither is a COVID keyword enough by itself.
- False-positive guard: do not mark harmless coping or wordplay as harmful just because it mentions COVID, vaccines, bleach, alcohol, death, China, quarantine, or public figures. Generic quarantine inconvenience jokes, self-deprecating isolation/snack/work-from-home jokes, neutral public-health reminders, Corona-beer/alcohol puns, abstract virus personification, one-off absurd vaccine side-effect jokes, and pure 2020-disaster humor are Claim_Harmless unless they include personal degradation, victim mockery, stigma, persuasive misinformation, or risky-behavior normalization.
- Retrieved HarM cases often contain both harmful and harmless rationales. Use them to compare mechanisms, not as label votes."""


def get_harm_boundary_rules(dataset_name: str = "FHM") -> str:
    """Return dataset-calibrated boundary text for prompts."""
    dataset_key = str(dataset_name).upper()
    if dataset_key == "FHM":
        return f"{HARM_BOUNDARY_RULES}\n\n{FHM_BOUNDARY_ADDENDUM}"
    if dataset_key == "HARM":
        return f"{HARM_BOUNDARY_RULES}\n\n{HARM_BOUNDARY_ADDENDUM}"
    return HARM_BOUNDARY_RULES
