# -*- coding: utf-8 -*-
"""
Memory-guided skill planning for Module 2.
"""
import json
import os
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

try:
    from openai import OpenAI
except (ModuleNotFoundError, ImportError):  # pragma: no cover - optional dependency
    OpenAI = None

from framework.config import DEFAULT_FRAMEWORK_CONFIG, DEFAULT_MODEL
from framework.boundary_rules import get_harm_boundary_rules
from framework.llm_utils import LLMCallError, LLMCaller, clamp_float, extract_json_object
from framework.memory import MemoryRetrievalResult, QuerySignature
from framework.skills import SkillCard, SkillType


@dataclass
class SkillPlan:
    """Execution plan generated by the skill planner."""

    selected_skills: List[SkillType]
    reasoning: str
    memory_patterns: List[str]
    execution_order: List[SkillType]
    confidence: float = 0.5

    def to_dict(self) -> Dict[str, Any]:
        return {
            "selected_skills": [skill.value for skill in self.selected_skills],
            "reasoning": self.reasoning,
            "memory_patterns": self.memory_patterns,
            "execution_order": [skill.value for skill in self.execution_order],
            "confidence": self.confidence,
        }

    def get_skill_list_string(self) -> str:
        return ", ".join(skill.value for skill in self.selected_skills)


class SkillPlanner:
    """
    Selects a small set of reasoning skills based on current problem signature
    and retrieved memory.
    """

    def __init__(
        self,
        client: Optional[OpenAI] = None,
        model: str = DEFAULT_MODEL,
        config: Optional[Any] = None,
        use_llm: bool = True,
        dataset_name: str = "FHM",
    ):
        self.config = config or DEFAULT_FRAMEWORK_CONFIG
        self.use_llm = use_llm
        self.dataset_name = dataset_name
        self.boundary_rules = get_harm_boundary_rules(dataset_name)
        self.dataset_planning_note = (
            "FHM planning note: many harmful cases are implicit image-text jokes. "
            "When text or visual summary suggests women/gender roles, sexual content, "
            "rape/consent, race/color, religion, nationality, disability, trans identity, "
            "animal comparison, violence, police harm, terrorism, atrocity, slavery, "
            "Holocaust, colonialism, or coded terms like dishwasher, kitchen, sandwich, "
            "vegetable, ape, monkey, goat, pig, tampon, or stop resisting, include "
            "target_boundary plus the relevant protected_group, misogyny, historical "
            "trivialization, image-text incongruity, or cultural-template skills."
            if dataset_name.upper() == "FHM" else (
                "HarM planning note: for COVID/political memes, include both the "
                "public-health perspective and the weak individual/organization harm "
                "perspective. Prefer target_boundary + political_criticism_boundary, "
                "and add historical_harm_trivialization when the meme mentions COVID, "
                "coronavirus, virus, masks, vaccines, testing, hoax, fake news, QAnon, "
                "disinfectant, bleach, cures, case counts, diagnosis, death, rallies, "
                "travel bans, or pandemic response. Select counter_speech_quoted_criticism "
                "only together with these boundary skills when the quoted/debunked content "
                "could still humiliate a named actor or amplify a dangerous phrase."
                if dataset_name.upper() == "HARM" else ""
            )
        )
        self.caller = LLMCaller(client=client, model=model, component_name="SkillPlanner")

    def plan(
        self,
        image_path: str,
        text: str,
        query_signature: QuerySignature,
        memory_result: MemoryRetrievalResult,
        skill_cards: List[SkillCard],
    ) -> SkillPlan:
        if self.use_llm:
            plan = self._plan_with_llm(
                image_path, text, query_signature, memory_result, skill_cards
            )
            if plan and plan.selected_skills:
                return self._normalize_plan(plan)
            raise LLMCallError("SkillPlanner did not return a valid skill plan.")
        return self._fallback_plan(query_signature, memory_result, skill_cards)

    def _plan_with_llm(
        self,
        image_path: str,
        text: str,
        query_signature: QuerySignature,
        memory_result: MemoryRetrievalResult,
        skill_cards: List[SkillCard],
    ) -> Optional[SkillPlan]:
        min_skills, max_skills = self._skill_bounds()
        skill_blocks = "\n\n".join(card.to_prompt_block() for card in skill_cards)
        prompt = f'''You are a Skill Planner for harmful meme analysis.

Your job is to select only the reasoning skills that are needed. Do not solve
the final classification.

Target meme text: "{text}"
[Image attached if available]

Query signature:
{json.dumps(query_signature.to_dict(), ensure_ascii=False, indent=2)}

Retrieved memory:
{memory_result.get_context_string(top_k_cases=5, top_k_insights=3, top_k_risks=3)}

Dataset boundary guidance:
{self.boundary_rules}

{self.dataset_planning_note}

Available skill cards:
{skill_blocks}

Select {min_skills}-{max_skills} skills. Prefer skills that can produce
verifiable evidence for a claim graph. Consider risk memory and retrieved
insights, but avoid irrelevant dimensions.

Return JSON only:
{{
  "memory_patterns": ["<patterns from retrieved memory that influence planning>"],
  "selected_skills": ["<skill_key>", "..."],
  "execution_order": ["<skill_key>", "..."],
  "reasoning": "<why these skills are needed and why omitted skills are less important>",
  "confidence": <0.0-1.0>
}}

Valid skill keys:
{", ".join(skill.value for skill in SkillType)}'''

        response = self.caller.call(
            prompt,
            image_path=image_path if os.path.exists(image_path) else None,
            max_tokens=1200,
        )
        data = extract_json_object(response)
        if not data:
            return None

        selected = self._parse_skill_list(data.get("selected_skills", []))
        order = self._parse_skill_list(data.get("execution_order", []))
        for skill in selected:
            if skill not in order:
                order.append(skill)
        return SkillPlan(
            selected_skills=selected,
            reasoning=str(data.get("reasoning", "")),
            memory_patterns=_as_list(data.get("memory_patterns")),
            execution_order=order,
            confidence=clamp_float(data.get("confidence", 0.5), 0.5),
        )

    def _fallback_plan(
        self,
        query_signature: QuerySignature,
        memory_result: MemoryRetrievalResult,
        skill_cards: List[SkillCard],
    ) -> SkillPlan:
        min_skills, max_skills = self._skill_bounds()
        scores: Dict[SkillType, float] = {card.skill_type: card.reliability for card in skill_cards}

        mechanisms = " ".join(query_signature.possible_harm_mechanisms).lower()
        entities = " ".join(query_signature.entities + query_signature.target_candidates).lower()
        signature_text = query_signature.to_retrieval_text().lower()

        def bump(skill: SkillType, value: float) -> None:
            scores[skill] = scores.get(skill, 0.0) + value

        if query_signature.target_candidates or "target" in signature_text:
            bump(SkillType.TARGET_BOUNDARY, 1.4)
        if any(token in mechanisms or token in entities for token in [
            "protected", "race", "religion", "gender", "nationality", "sexuality",
            "disability", "black", "muslim", "gay", "lesbian",
        ]):
            bump(SkillType.PROTECTED_GROUP_ATTRIBUTION, 1.5)
            bump(SkillType.TARGET_BOUNDARY, 0.6)
        if any(token in mechanisms or token in entities for token in [
            "misogyny", "women", "woman", "girl", "lesbian", "feminism",
            "sexualization", "wife", "female", "tampon", "dishwasher", "kitchen",
            "sandwich",
        ]):
            bump(SkillType.MISOGYNISTIC_FRAMING, 1.7)
            if self.dataset_name.upper() == "FHM":
                bump(SkillType.TARGET_BOUNDARY, 0.6)
        if any(token in mechanisms or token in entities for token in [
            "political", "trump", "biden", "president", "government", "election",
            "organization", "public figure", "candidate", "administration",
        ]):
            bump(SkillType.POLITICAL_CRITICISM_BOUNDARY, 1.5)
            if self.dataset_name.upper() == "HARM":
                bump(SkillType.TARGET_BOUNDARY, 0.8)
        if any(token in mechanisms for token in [
            "historical_harm", "health_or_disaster", "violence", "trivialization",
        ]):
            bump(SkillType.HISTORICAL_HARM_TRIVIALIZATION, 1.3)
        if self.dataset_name.upper() == "FHM" and any(token in signature_text for token in [
            "women", "woman", "girl", "wife", "female", "lesbian", "gay",
            "trans", "tranny", "non binary", "disabled", "deaf", "retarded",
            "black", "white", "muslim", "islam", "jew", "jewish", "asian",
            "mexican", "immigrant", "race", "skin", "crime", "virgin",
            "dishwasher", "kitchen", "sandwich", "tampon", "vegetable",
            "ape", "monkey", "goat", "pig", "animal", "sheep", "dog",
            "rape", "consent", "handjob", "porn", "sex", "bitch", "whore",
            "beat", "kill", "shoot", "bomb", "suicide", "terrorist", "isis",
            "hitler", "nazi", "klan", "slave", "holocaust", "colonialism",
            "stop resisting",
        ]):
            bump(SkillType.TARGET_BOUNDARY, 0.8)
            bump(SkillType.IMAGE_TEXT_INCONGRUITY, 0.7)
            bump(SkillType.CULTURAL_TEMPLATE_INTERPRETATION, 0.4)
            if any(token in signature_text for token in [
                "black", "white", "muslim", "islam", "jew", "jewish", "asian",
                "mexican", "immigrant", "race", "skin", "gay", "lesbian", "trans",
                "non binary", "disabled", "deaf", "retarded",
            ]):
                bump(SkillType.PROTECTED_GROUP_ATTRIBUTION, 1.0)
            if any(token in signature_text for token in [
                "women", "woman", "girl", "wife", "female", "dishwasher",
                "kitchen", "sandwich", "tampon", "handjob", "porn", "sex",
                "bitch", "whore",
            ]):
                bump(SkillType.MISOGYNISTIC_FRAMING, 1.0)
            if any(token in signature_text for token in [
                "beat", "kill", "shoot", "bomb", "suicide", "terrorist", "isis",
                "hitler", "nazi", "klan", "slave", "holocaust", "colonialism",
                "stop resisting",
            ]):
                bump(SkillType.HISTORICAL_HARM_TRIVIALIZATION, 1.0)
        if self.dataset_name.upper() == "HARM" and any(token in signature_text for token in [
            "covid", "coronavirus", "virus", "mask", "vaccine", "testing",
            "test positive", "positive for covid", "hoax", "fake news", "qanon",
            "deep state", "disinfectant", "bleach", "cure", "case count", "death",
            "die", "pandemic", "quarantine", "rally", "travel ban",
        ]):
            bump(SkillType.POLITICAL_CRITICISM_BOUNDARY, 1.0)
            bump(SkillType.HISTORICAL_HARM_TRIVIALIZATION, 1.0)
            bump(SkillType.TARGET_BOUNDARY, 0.5)
        relation = query_signature.image_text_relation.lower()
        if (
            "incongruent" in relation
            or "contradict" in relation
            or "image_text" in mechanisms
        ):
            bump(SkillType.IMAGE_TEXT_INCONGRUITY, 1.6)
        if any(token in signature_text for token in [
            "template", "celebrity", "movie", "slang", "dog whistle", "meme",
        ]):
            bump(SkillType.CULTURAL_TEMPLATE_INTERPRETATION, 1.1)
        if any(token in signature_text for token in [
            "quote", "quoted", "critique", "criticizes", "satire", "not racist",
            "mocking hate",
        ]):
            bump(SkillType.COUNTER_SPEECH_QUOTED_CRITICISM, 1.2)

        for row in memory_result.risk_memories:
            for skill_key in row.item.recommended_skills:
                try:
                    bump(SkillType(skill_key), 0.5 * row.score)
                except ValueError:
                    continue

        for row in memory_result.insight_memories:
            text = row.item.retrieval_text().lower()
            for skill_type in SkillType:
                if any(part in text for part in skill_type.value.split("_")):
                    bump(skill_type, 0.15 * row.score)

        ranked = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        selected = [skill for skill, _ in ranked[:max_skills]]
        if len(selected) < min_skills:
            for skill in [
                SkillType.TARGET_BOUNDARY,
                SkillType.IMAGE_TEXT_INCONGRUITY,
                SkillType.PROTECTED_GROUP_ATTRIBUTION,
                SkillType.CULTURAL_TEMPLATE_INTERPRETATION,
            ]:
                if skill not in selected:
                    selected.append(skill)
                if len(selected) >= min_skills:
                    break

        patterns = []
        patterns.extend(row.item.title for row in memory_result.insight_memories[:3])
        patterns.extend(row.item.risk_type for row in memory_result.risk_memories[:3])
        return SkillPlan(
            selected_skills=selected[:max_skills],
            reasoning=(
                "Fallback planner selected skills by matching query signature "
                "mechanisms, retrieved insight memory, and risk memory."
            ),
            memory_patterns=patterns,
            execution_order=selected[:max_skills],
            confidence=0.6,
        )

    def _normalize_plan(self, plan: SkillPlan) -> SkillPlan:
        min_skills, max_skills = self._skill_bounds()
        selected: List[SkillType] = []
        for skill in plan.selected_skills:
            if skill not in selected:
                selected.append(skill)

        for fallback in [
            SkillType.TARGET_BOUNDARY,
            SkillType.IMAGE_TEXT_INCONGRUITY,
            SkillType.PROTECTED_GROUP_ATTRIBUTION,
            SkillType.CULTURAL_TEMPLATE_INTERPRETATION,
        ]:
            if len(selected) >= min_skills:
                break
            if fallback not in selected:
                selected.append(fallback)

        selected = selected[:max_skills]
        order = [skill for skill in plan.execution_order if skill in selected]
        for skill in selected:
            if skill not in order:
                order.append(skill)

        plan.selected_skills = selected
        plan.execution_order = order
        return plan

    def _skill_bounds(self) -> Tuple[int, int]:
        fixed = getattr(self.config, "fixed_skill_count", None)
        if fixed is None:
            fixed = getattr(self.config, "fixed_tool_count", None)
        if fixed:
            return fixed, fixed
        min_skills = getattr(self.config, "min_skills_to_select", None)
        max_skills = getattr(self.config, "max_skills_to_select", None)
        if min_skills is None:
            min_skills = getattr(self.config, "min_tools_to_select", 2)
        if max_skills is None:
            max_skills = getattr(self.config, "max_tools_to_select", 4)
        min_skills = max(1, int(min_skills))
        max_skills = max(min_skills, int(max_skills))
        return min_skills, max_skills

    @staticmethod
    def _parse_skill_list(values: Any) -> List[SkillType]:
        if isinstance(values, str):
            values = re.split(r"[,;\n]+", values)
        parsed = []
        for value in values or []:
            key = str(value).strip().lower()
            if not key:
                continue
            try:
                skill = SkillType(key)
            except ValueError:
                skill = None
                for candidate in SkillType:
                    if key in candidate.value or candidate.value in key:
                        skill = candidate
                        break
            if skill and skill not in parsed:
                parsed.append(skill)
        return parsed


def _as_list(value: Any) -> List[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v) for v in value if str(v).strip()]
    if isinstance(value, str):
        return [value] if value.strip() else []
    return [str(value)]
